### ISSUE TITLE
Issues with giving Webhook permissions to create poll.

### ISSUE THREAD

**Issue by shotah** [JohnnyJayJay/instant-poll#17]
Unsure of how to enable a webhook to create a poll. 

Looking at creating a poll for any issues that have the enhancement label. I need to spend some more time with the event api to see how to pull out the labels and subjects, but currently its not able to create a poll. I just see the plain text pop out into discord.

Thanks!

```yaml
on:
  issues:
    types: [labeled]

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  poll:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: poll
        # if: contains(github.event.label, 'enhancement')
        uses: Ilshidur/action-discord@master
        with:
          args: "/poll create question: ${{ github.event }} 1: Interested 2: Uninterested 3: Not needed"
```
